# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

target 'seaHorseTheater' do
  # Comment the next line if you don't want to use dynamic frameworks
    # use_frameworks!
  # Pods for seaHorseTheater
  
    pod 'Ads-CN', '6.4.1.7' #为保证兼容性 建议使用广告SDK版本
    pod 'TTSDKFramework', '1.42.3.4-premium', :subspecs => [ 'Player' ]
    pod 'PangrowthX', '2.6.0.0', :subspecs => [ 'shortplay' ]
    pod 'Reachability', '3.2'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
      target.build_configurations.each do |config|
        config.build_settings["ENABLE_MODULE_VERIFIER"] = "NO"
        config.build_settings["ENABLE_USER_SCRIPT_SANDBOXING"] = "NO"
        config.build_settings["CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER"] = "NO"
      end
    end
  end
end
